name: depcheck
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: depcheck
      uses: theahura/depcheck-action@main
      with:
        args: --skip-missing true
